### ISSUE TITLE
feat: replace fast-write-atomic with steno

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/js-stores#284]
See https://github.com/SgtPooki/fast-write-atomic#uint8array

| Task Name                                             | ops/sec | Average Time (ns)  | Margin | Samples |
|-------------------------------------------------------|---------|--------------------|--------|---------|
| Uint8Array - write-file-atomic                        | 101     | 9853620.467916131  | ±1.15% | 1000    |
| Uint8Array - fast-write-atomic                        | 106     | 9421993.666924536  | ±1.30% | 1000    |
| Uint8Array - atomically                               | 101     | 9857824.475903064  | ±1.16% | 1000    |
| Uint8Array - steno                                    | 2,937   | 340472.6759530604  | ±4.23% | 1000    |
| Uint8Array - steno (cached writers)                   | 3,037   | 329200.16099512577 | ±6.35% | 1000    |
| Uint8Array - @sgtpooki/steno-patched                  | 2,940   | 340053.3969886601  | ±9.02% | 1000    |
| Uint8Array - @sgtpooki/steno-patched (cached writers) | 2,566   | 389624.0490563214  | ±8.57% | 1000    |

```[tasklist]
### Tasks
- [x] update steno to support more than strings (it should support everything fsPromises.writeFile supports) - see https://github.com/SgtPooki/steno
- [x] replace https://github.com/ipfs/js-stores/blob/7dad9a43fdec367895467752a6fee3ac7f912ca4/packages/blockstore-fs/src/index.ts#L22
- [x] replace https://github.com/ipfs/js-stores/blob/7dad9a43fdec367895467752a6fee3ac7f912ca4/packages/datastore-fs/src/index.ts#L22
```

related: https://github.com/ipfs/helia/pull/346#issuecomment-1856615727

**Comment by achingbrain** [comment]
Fixed by #285

**Comment by achingbrain** [comment]
Ah, no, #285 merged the steno impl into the PR with the tests
